workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 45
    environment:
      android_signing:
        - esoterica
    scripts:
      - name: Install dependencies
        script: |
          yarn install

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
