workflows:
  android-react-native:
    name: Android APK + AAB Build (React Native + TypeScript)
    max_build_duration: 45
    environment:
      vars:
        PACKAGE_MANAGER: yarn
        NODE_VERSION: 18.18.2
      node: $NODE_VERSION
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: |
          npm install -g corepack
          corepack enable
          yarn install

      - name: Clean and set Gradle permissions
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
